services:
  app:
    build: .
    image: local-dockerlempapp:latest
    ports:
      - "8080:80"
      - "${EXTERNAL_PORT:-8443}:443"
    volumes:
      - ./app:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tenants:/tenants
      - ./compose.tenant.yaml:/home/ubuntu/Workspace/compose.tenant.yaml
      - sqlite_data:/var/sqlite
      - ./sqlite conf:/var/www/html/sqlite conf
    environment:
      DOCKER_CONFIG: /tmp/.docker
      TZ: Australia/Sydney
      DB_VENDOR: sqlite
      TARGET_ENV: ${TARGET_ENV:-dev}
      EXTERNAL_PORT: ${EXTERNAL_PORT}
      TENANT_DB_NAME: ${TENANT_DB_NAME}
      TENANT_DB_USER: ${TENANT_DB_USER}
      TENANT_DB_PASS: ${TENANT_DB_PASS}
    networks:
      - stack-network
      - superhost-network
    deploy:
      resources:
        limits:
          memory: 256M
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.sqlite.db
    volumes:
      - sqlite_data:/var/sqlite
    networks:
      - stack-network
    deploy:
      resources:
        limits:
          memory: 64M

volumes:
  sqlite_data:
networks:
  stack-network:
    driver: bridge
  superhost-network:
    external: true
    name: superhost-network
