services:
  app:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./app:/var/www/html
    environment:
      TZ: Australia/Sydney
      DB_VENDOR: mysql
      DB_HOST: db
      DB_NAME: stackDB
      DB_USER: docker_user_lemp
      DB_PASS: docker_user_lemp
    networks:
      - stack-network
    deploy:
      resources:
        limits:
          memory: 256M
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: docker_lemp
      MYSQL_DATABASE: stackDB
      MYSQL_USER: docker_user_lemp
      MYSQL_PASSWORD: docker_user_lemp
      TZ: Australia/Sydney
    volumes:
      - db_data:/var/lib/mysql
      - ./conf/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - stack-network
    deploy:
      resources:
        limits:
          memory: 512M
volumes:
  db_data:
networks:
  stack-network:
    driver: bridge