services:
  app:
    build: .
    image: local-dockerlempapp:latest
    ports:
      - "8080:80"
      - "${EXTERNAL_PORT:-8443}:443"
    volumes:
      - ./app:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tenants:/tenants
      - ./compose.tenant.yaml:/home/ubuntu/Workspace/compose.tenant.yaml
    environment:
      DOCKER_CONFIG: /tmp/.docker
      TZ: Australia/Sydney
      DB_VENDOR: mysql
      DB_HOST: db
      TARGET_ENV: ${TARGET_ENV:-dev}
      EXTERNAL_PORT: ${EXTERNAL_PORT}
      TENANT_DB_NAME: ${TENANT_DB_NAME}
      TENANT_DB_USER: ${TENANT_DB_USER}
      TENANT_DB_PASS: ${TENANT_DB_PASS}
    networks:
      - stack-network
      - superhost-network
    deploy:
      resources:
        limits:
          memory: 256M
  db:

    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${TENANT_DB_ROOT}
      MYSQL_DATABASE: ${TENANT_DB_NAME}
      MYSQL_USER: ${TENANT_DB_USER}
      MYSQL_PASSWORD: ${TENANT_DB_PASS}
      TZ: Australia/Sydney
    volumes:
      - maria_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - stack-network
    deploy:
      resources:
        limits:
          memory: 512M
volumes:
  maria_db_data:
networks:
  stack-network:
    driver: bridge
  superhost-network:
    external: true
    name: superhost-network