services:
  app:
    build: .
    image: local-dockerlempapp:latest
    ports:
      - "8080:80"
      - "${EXTERNAL_PORT:-8443}:443"
    volumes:
      - ./app:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tenants:/tenants
      - ./compose.tenant.yaml:/home/ubuntu/Workspace/compose.tenant.yaml
    environment:
      DOCKER_CONFIG: /tmp/.docker
      TZ: Australia/Sydney
      DB_VENDOR: pgsql
      DB_HOST: db
      TARGET_ENV: ${TARGET_ENV:-dev}
      EXTERNAL_PORT: ${EXTERNAL_PORT}
      TENANT_DB_NAME: ${TENANT_DB_NAME}
      TENANT_DB_USER: ${TENANT_DB_USER}
      TENANT_DB_PASS: ${TENANT_DB_PASS}
    networks:
      - stack-network
      - superhost-network
    deploy:
      resources:
        limits:
          memory: 256M
  db:
    image: postgres:latest
    environment:
      #MARIADB_ROOT_PASSWORD: docker_lemp
      POSTGRES_DB: ${TENANT_DB_NAME}
      POSTGRES_USER: ${TENANT_DB_USER}
      POSTGRES_PASSWORD: ${TENANT_DB_PASS}
      TZ: Australia/Sydney
    volumes:
      - postgres_db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - stack-network
    deploy:
      resources:
        limits:
          memory: 512M
volumes:
  postgres_db_data:
networks:
  stack-network:
    driver: bridge
  superhost-network:
    external: true
    name: superhost-network
