services:
  app:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./app:/var/www/html
    environment:
      TZ: Australia/Sydney
      DB_VENDOR: mysql
      DB_HOST: db
      DB_NAME: stackDB
      DB_USER: docker_user_lemp
      DB_PASS: docker_user_lemp
    networks:
      - stack-network
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: docker_lemp
      MARIADB_DATABASE: stackDB
      MARIADB_USER: docker_user_lemp
      MARIADB_PASSWORD: docker_user_lemp
      TZ: Australia/Sydney
    volumes:
      - maria_db_data:/var/lib/mysql
      - ./conf/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - stack-network
volumes:
  maria_db_data:
networks:
  stack-network:
    driver: bridge