services:
  app:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./app:/var/www/html
    environment:
      TZ: Australia/Sydney
      DB_VENDOR: pgsql
      DB_HOST: db
      DB_NAME: stackDB
      DB_USER: docker_user_lemp
      DB_PASS: docker_user_lemp
    networks:
      - stack-network
  db:
    image: postgres:latest
    environment:
      #MARIADB_ROOT_PASSWORD: docker_lemp
      POSTGRES_DB: stackDB
      POSTGRES_USER: docker_user_lemp
      POSTGRES_PASSWORD: docker_user_lemp
      TZ: Australia/Sydney
    volumes:
      - postgres_db_data:/var/lib/postgresql
      - ./postgres conf/common/01_db_ddl.sql:/docker-entrypoint-initdb.d/01_db_ddl.sql
      - ./postgres conf/common/02_db_dml.sql:/docker-entrypoint-initdb.d/02_db_dml.sql
      - ./conf/${TARGET_ENV}/03_db_dml.sql:/docker-entrypoint-initdb.d/03_db_dml.sql:ro
    ports:
      - "5432:5432"
    networks:
      - stack-network
volumes:
  postgres_db_data:
networks:
  stack-network:
    driver: bridge