CREATE DATABASE stackDB;

CREATE TABLE appUsers(
    auPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(32) NOT NULL,
    age INT NOT NULL,
    city VARCHAR(32) NOT NULL,
    username VARCHAR(16) NOT NULL,
    password VARCHAR(256) NOT NULL,
    email VARCHAR(32) NOT NULL,
    dateAdded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateVerified TIMESTAMP,
    verified BOOLEAN NOT NULL DEFAULT true,
    PRIMARY KEY(auPK)
);

CREATE TABLE tblPages (
    pagPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    pagCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pagUpdated TIMESTAMP NULL,
    pagDeleted TIMESTAMP NULL,
    pagAuthorFK INT NOT NULL,
    pagTitle VARCHAR(128) NOT NULL,
    pagSlug VARCHAR(128) NULL,
    PRIMARY KEY(pagPK)
);

CREATE TABLE tblElements (
    elePK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    eleType VARCHAR(32) NOT NULL,
    eleContent TEXT NULL,
    eleCSSClasses VARCHAR(255) NULL,
    eleParentFK INT NULL DEFAULT NULL,
    eleCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(elePK),
    FOREIGN KEY(eleParentFK) REFERENCES tblElements(elePK) ON DELETE CASCADE
);

CREATE TABLE brgPageElements (
    pelPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    pelPageFK INT NOT NULL,
    pelElementFK INT NOT NULL,
    pelOrder INT NOT NULL,
    PRIMARY KEY(pelPK),
    FOREIGN KEY(pelPageFK) REFERENCES tblPages(pagPK) ON DELETE CASCADE,
    FOREIGN KEY(pelElementFK) REFERENCES tblElements(elePK) ON DELETE CASCADE
);
CREATE TABLE tblSession(
    sessPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    sessCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sessUpdated TIMESTAMP NULL,
    sessDeleted TIMESTAMP NULL,
    sessChars VARCHAR(64) NOT NULL,
    sessUser INT NULL,
    sessTransactionActive INT NOT NULL,
    PRIMARY KEY(sessPK)
);

CREATE TABLE tblSessionAtt(
    sattPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    sattSessionFK INT NOT NULL,
    sattDisc CHAR(1) NOT NULL,
    sattKey VARCHAR(32) NOT NULL,
    sattPrimaryValueFK INT NOT NULL,
    PRIMARY KEY(sattPK)
);

CREATE TABLE tblSessionAttValue(
    sattvPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    sattvAttFK INT NOT NULL,
    sattvValueFK INT NULL,
    sattvValue VARCHAR(128) NULL,
    PRIMARY KEY(sattvPK)
);

CREATE TABLE sysConfig(
    scPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    scName VARCHAR(32) NOT NULL,
    scValue VARCHAR(128) NOT NULL,
    PRIMARY KEY(scPK)
);

CREATE TABLE tblNavBar(
    nbPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    nbText VARCHAR(32) NOT NULL,
    nbDiscriminator CHAR(1) NOT NULL,
    nbPageFK INT NULL,
    nbPath VARCHAR(64) NULL,
    nbControllerClass VARCHAR(64) NULL,
    nbProtected BOOLEAN NOT NULL,
    nbOrder INT NOT NULL,
    nbParentFK INT NULL DEFAULT NULL,
    PRIMARY KEY(nbPK),
    FOREIGN KEY(nbParentFK) REFERENCES tblNavBar(nbPK) ON DELETE SET NULL,
    FOREIGN KEY(nbPageFK) REFERENCES tblPages(pagPK) ON DELETE SET NULL
);

CREATE UNIQUE INDEX idx_session_chars ON tblSession(sessChars);
CREATE INDEX idx_session_att_lookup ON tblSessionAtt(sattSessionFK, sattKey, sattDisc);
CREATE INDEX idx_session_val_lookup ON tblSessionAttValue(sattvAttFK);

CREATE TABLE httpAction(
    haPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    haDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    haSessionFK INT NOT NULL,
    haUserFK INT NULL,
    haIP VARCHAR(45) NOT NULL,
    haURL VARCHAR(512) NOT NULL,
    haReferrer VARCHAR(512) NULL,
    haMethod VARCHAR(8) NOT NULL,
    haUserAgent VARCHAR(512) NOT NULL,
    haHeaders TEXT NULL,
    haWafRuleTriggered VARCHAR(255) NULL,
    haWafPayload TEXT NULL,
    PRIMARY KEY(haPK)
);

CREATE TABLE phpErrorLog (
  pelPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  pelTimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pelSeverity VARCHAR(32) NOT NULL,
  pelMessage TEXT NOT NULL,
  pelFile VARCHAR(512) NOT NULL,
  pelLine INT NOT NULL,
  PRIMARY KEY(pelPK)
);

CREATE TABLE tblForm(
    tfPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    tfName VARCHAR(32) NOT NULL,
    tfAction VARCHAR(255) NULL,
    tfReadOnly BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY(tfPK)
);

CREATE TABLE tblColumns(
    tcPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    tcFormFK INT NOT NULL,
    tcName VARCHAR(32) NOT NULL,
    tcLabel VARCHAR(64) NOT NULL,
    tcType VARCHAR(32) NOT NULL,
    tcRules TEXT NOT NULL,
    tcOrder INT NOT NULL,
    PRIMARY KEY(tcPK),
    FOREIGN KEY(tcFormFK) REFERENCES tblForm(tfPK) ON DELETE CASCADE
);

CREATE TABLE banned_ips(
    biPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    biIP VARCHAR(45) NOT NULL,
    biReason VARCHAR(255) NOT NULL,
    biExpires TIMESTAMP NOT NULL,
    biDateAdded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(biPK)
);

CREATE TABLE event_store(
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    aggregate_id INT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload TEXT NOT NULL,
    previous_payload TEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    user_id INT NULL,
    is_reversal BOOLEAN NOT NULL DEFAULT false,
    predecessor_id INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

/* sample data for Block - Graph */

CREATE TABLE tblAnalytics (
    anaPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    anaLabel VARCHAR(32) NOT NULL,
    anaValue INT NOT NULL,
    anaCategory VARCHAR(32) NOT NULL,
    anaDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(anaPK)
);

/* END sample data for Block - Graph */

CREATE TABLE absChildServices (
    csPK INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    csCreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    csCreatedByFK INT NOT NULL,
    csUpdatedDate TIMESTAMP NULL,
    csAdminFK INT NOT NULL,
    csUptimeDate TIMESTAMP NULL,
    csCheckDate TIMESTAMP NULL,
    csName VARCHAR(32) NOT NULL,
    csStatus CHAR(1) NOT NULL,
    csDockerID VARCHAR(64) NULL,
    csSubdomain VARCHAR(64) NULL,
    csFailureCount INT NOT NULL DEFAULT 0,
    PRIMARY KEY(csPK)
);

